### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by Djepeto** [contentacms/contenta_docker#15] opened 2018-03-05 15:17 UTC
Cloned the repository. 
Tried docker-compose build, it managed to go over the first step, but it breaks on the second step.

![image](https://user-images.githubusercontent.com/35599403/36982654-a59323b8-2090-11e8-86d8-67a92f40f727.png)

**Comment by e0ipso** [comment] 2018-03-06 05:52
This seems to be reporting a network error downloading the necessary requirements. Did you retry with the same result?

**Comment by pcambra** [comment] 2018-06-20 07:46
Can't really reproduce this and indeed seems like network problems, closing it, feel free to report back with more details.

**Closed as completed by pcambra** 2018-06-20 07:46 UTC
